# TCL File Generated by Component Editor 20.1
# Wed Dec 03 23:12:54 CST 2025
# DO NOT MODIFY


# 
# downscaler_top "Image Downscaler Top" v1.0
# TEC Costa Rica 2025.12.03.23:12:54
# Image Downscaler Accelerator with SIMD support
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module downscaler_top
# 
set_module_property DESCRIPTION "Image Downscaler Accelerator with SIMD support"
set_module_property NAME downscaler_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "DSA Accelerators"
set_module_property AUTHOR "TEC Costa Rica"
set_module_property DISPLAY_NAME "Image Downscaler Top"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL downscaler_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file downscaler_top.sv SYSTEM_VERILOG PATH src/rtl/downscaler_top.sv TOP_LEVEL_FILE
add_fileset_file accelerator_csr_bridge.sv SYSTEM_VERILOG PATH src/rtl/accelerator_csr_bridge.sv
add_fileset_file simd_downscaler.sv SYSTEM_VERILOG PATH src/rtl/simd_downscaler.sv
add_fileset_file pixel_fetch_fsm.sv SYSTEM_VERILOG PATH src/rtl/pixel_fetch_fsm.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL downscaler_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file downscaler_top.sv SYSTEM_VERILOG PATH src/rtl/downscaler_top.sv TOP_LEVEL_FILE
add_fileset_file accelerator_csr_bridge.sv SYSTEM_VERILOG PATH src/rtl/accelerator_csr_bridge.sv
add_fileset_file simd_downscaler.sv SYSTEM_VERILOG PATH src/rtl/simd_downscaler.sv
add_fileset_file pixel_fetch_fsm.sv SYSTEM_VERILOG PATH src/rtl/pixel_fetch_fsm.sv


# 
# parameters
# 
add_parameter LANES INTEGER 4 "Number of SIMD lanes for parallel pixel processing"
set_parameter_property LANES DEFAULT_VALUE 4
set_parameter_property LANES DISPLAY_NAME "SIMD Lanes"
set_parameter_property LANES TYPE INTEGER
set_parameter_property LANES UNITS None
set_parameter_property LANES ALLOWED_RANGES {2 4 8}
set_parameter_property LANES DESCRIPTION "Number of SIMD lanes for parallel pixel processing"
set_parameter_property LANES HDL_PARAMETER true
add_parameter Q INTEGER 8 "Number of fractional bits for Q8.8 fixed-point format"
set_parameter_property Q DEFAULT_VALUE 8
set_parameter_property Q DISPLAY_NAME "Fractional Bits (Q format)"
set_parameter_property Q TYPE INTEGER
set_parameter_property Q UNITS None
set_parameter_property Q ALLOWED_RANGES {4 8 12 16}
set_parameter_property Q DESCRIPTION "Number of fractional bits for Q8.8 fixed-point format"
set_parameter_property Q HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point csr_slave
# 
add_interface csr_slave avalon end
set_interface_property csr_slave addressUnits SYMBOLS
set_interface_property csr_slave associatedClock clock
set_interface_property csr_slave associatedReset reset
set_interface_property csr_slave bitsPerSymbol 8
set_interface_property csr_slave burstOnBurstBoundariesOnly false
set_interface_property csr_slave burstcountUnits WORDS
set_interface_property csr_slave explicitAddressSpan 0
set_interface_property csr_slave holdTime 0
set_interface_property csr_slave linewrapBursts false
set_interface_property csr_slave maximumPendingReadTransactions 0
set_interface_property csr_slave maximumPendingWriteTransactions 0
set_interface_property csr_slave readLatency 0
set_interface_property csr_slave readWaitStates 0
set_interface_property csr_slave readWaitTime 0
set_interface_property csr_slave setupTime 0
set_interface_property csr_slave timingUnits Cycles
set_interface_property csr_slave writeWaitTime 0
set_interface_property csr_slave ENABLED true
set_interface_property csr_slave EXPORT_OF ""
set_interface_property csr_slave PORT_NAME_MAP ""
set_interface_property csr_slave CMSIS_SVD_VARIABLES ""
set_interface_property csr_slave SVD_ADDRESS_GROUP ""

add_interface_port csr_slave csr_address address Input 12
add_interface_port csr_slave csr_read read Input 1
add_interface_port csr_slave csr_write write Input 1
add_interface_port csr_slave csr_writedata writedata Input 32
add_interface_port csr_slave csr_byteenable byteenable Input 4
add_interface_port csr_slave csr_readdata readdata Output 32
add_interface_port csr_slave csr_waitrequest waitrequest Output 1
set_interface_assignment csr_slave embeddedsw.configuration.isFlash 0
set_interface_assignment csr_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point sdram_master
# 
add_interface sdram_master avalon start
set_interface_property sdram_master addressUnits SYMBOLS
set_interface_property sdram_master associatedClock clock
set_interface_property sdram_master associatedReset reset
set_interface_property sdram_master bitsPerSymbol 8
set_interface_property sdram_master burstOnBurstBoundariesOnly false
set_interface_property sdram_master burstcountUnits WORDS
set_interface_property sdram_master doStreamReads false
set_interface_property sdram_master doStreamWrites false
set_interface_property sdram_master holdTime 0
set_interface_property sdram_master linewrapBursts false
set_interface_property sdram_master maximumPendingReadTransactions 0
set_interface_property sdram_master maximumPendingWriteTransactions 0
set_interface_property sdram_master readLatency 0
set_interface_property sdram_master readWaitTime 1
set_interface_property sdram_master setupTime 0
set_interface_property sdram_master timingUnits Cycles
set_interface_property sdram_master writeWaitTime 0
set_interface_property sdram_master ENABLED true
set_interface_property sdram_master EXPORT_OF ""
set_interface_property sdram_master PORT_NAME_MAP ""
set_interface_property sdram_master CMSIS_SVD_VARIABLES ""
set_interface_property sdram_master SVD_ADDRESS_GROUP ""

add_interface_port sdram_master sdram_address address Output 32
add_interface_port sdram_master sdram_read read Output 1
add_interface_port sdram_master sdram_write write Output 1
add_interface_port sdram_master sdram_writedata writedata Output 16
add_interface_port sdram_master sdram_readdata readdata Input 16
add_interface_port sdram_master sdram_waitrequest waitrequest Input 1
add_interface_port sdram_master sdram_readdatavalid readdatavalid Input 1
add_interface_port sdram_master sdram_byteenable byteenable Output 2

