// mi_sdram.v

// Generated using ACDS version 20.1 711

`timescale 1 ps / 1 ps
module mi_sdram (
		input  wire        clk_clk,                         //               clk.clk
		input  wire        clk_0_clk,                       //             clk_0.clk
		output wire [37:0] fpga_logic_master_address,       // fpga_logic_master.address
		output wire [9:0]  fpga_logic_master_burstcount,    //                  .burstcount
		output wire        fpga_logic_master_read,          //                  .read
		output wire        fpga_logic_master_write,         //                  .write
		input  wire        fpga_logic_master_waitrequest,   //                  .waitrequest
		input  wire        fpga_logic_master_readdatavalid, //                  .readdatavalid
		output wire [3:0]  fpga_logic_master_byteenable,    //                  .byteenable
		input  wire [31:0] fpga_logic_master_readdata,      //                  .readdata
		output wire [31:0] fpga_logic_master_writedata,     //                  .writedata
		output wire        fpga_logic_master_lock,          //                  .lock
		output wire        fpga_logic_master_debugaccess,   //                  .debugaccess
		input  wire        reset_reset_n,                   //             reset.reset_n
		input  wire        reset_0_reset_n,                 //           reset_0.reset_n
		output wire [11:0] sdram_wire_addr_addr,            //   sdram_wire_addr.addr
		output wire [1:0]  sdram_wire_addr_ba,              //                  .ba
		output wire        sdram_wire_addr_cas_n,           //                  .cas_n
		output wire        sdram_wire_addr_cke,             //                  .cke
		output wire        sdram_wire_addr_cs_n,            //                  .cs_n
		inout  wire [31:0] sdram_wire_addr_dq,              //                  .dq
		output wire [3:0]  sdram_wire_addr_dqm,             //                  .dqm
		output wire        sdram_wire_addr_ras_n,           //                  .ras_n
		output wire        sdram_wire_addr_we_n             //                  .we_n
	);

	wire  [31:0] master_0_master_readdata;                                  // mm_interconnect_0:master_0_master_readdata -> master_0:master_readdata
	wire         master_0_master_waitrequest;                               // mm_interconnect_0:master_0_master_waitrequest -> master_0:master_waitrequest
	wire  [31:0] master_0_master_address;                                   // master_0:master_address -> mm_interconnect_0:master_0_master_address
	wire         master_0_master_read;                                      // master_0:master_read -> mm_interconnect_0:master_0_master_read
	wire   [3:0] master_0_master_byteenable;                                // master_0:master_byteenable -> mm_interconnect_0:master_0_master_byteenable
	wire         master_0_master_readdatavalid;                             // mm_interconnect_0:master_0_master_readdatavalid -> master_0:master_readdatavalid
	wire         master_0_master_write;                                     // master_0:master_write -> mm_interconnect_0:master_0_master_write
	wire  [31:0] master_0_master_writedata;                                 // master_0:master_writedata -> mm_interconnect_0:master_0_master_writedata
	wire         mm_interconnect_0_new_sdram_controller_0_s1_chipselect;    // mm_interconnect_0:new_sdram_controller_0_s1_chipselect -> new_sdram_controller_0:az_cs
	wire  [31:0] mm_interconnect_0_new_sdram_controller_0_s1_readdata;      // new_sdram_controller_0:za_data -> mm_interconnect_0:new_sdram_controller_0_s1_readdata
	wire         mm_interconnect_0_new_sdram_controller_0_s1_waitrequest;   // new_sdram_controller_0:za_waitrequest -> mm_interconnect_0:new_sdram_controller_0_s1_waitrequest
	wire  [21:0] mm_interconnect_0_new_sdram_controller_0_s1_address;       // mm_interconnect_0:new_sdram_controller_0_s1_address -> new_sdram_controller_0:az_addr
	wire         mm_interconnect_0_new_sdram_controller_0_s1_read;          // mm_interconnect_0:new_sdram_controller_0_s1_read -> new_sdram_controller_0:az_rd_n
	wire   [3:0] mm_interconnect_0_new_sdram_controller_0_s1_byteenable;    // mm_interconnect_0:new_sdram_controller_0_s1_byteenable -> new_sdram_controller_0:az_be_n
	wire         mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid; // new_sdram_controller_0:za_valid -> mm_interconnect_0:new_sdram_controller_0_s1_readdatavalid
	wire         mm_interconnect_0_new_sdram_controller_0_s1_write;         // mm_interconnect_0:new_sdram_controller_0_s1_write -> new_sdram_controller_0:az_wr_n
	wire  [31:0] mm_interconnect_0_new_sdram_controller_0_s1_writedata;     // mm_interconnect_0:new_sdram_controller_0_s1_writedata -> new_sdram_controller_0:az_data
	wire         rst_controller_reset_out_reset;                            // rst_controller:reset_out -> [merlin_master_translator_0:reset, mm_interconnect_0:master_0_clk_reset_reset_bridge_in_reset_reset, mm_interconnect_0:new_sdram_controller_0_reset_reset_bridge_in_reset_reset, new_sdram_controller_0:reset_n]

	mi_sdram_master_0 #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) master_0 (
		.clk_clk              (clk_0_clk),                     //          clk.clk
		.clk_reset_reset      (~reset_0_reset_n),              //    clk_reset.reset
		.master_address       (master_0_master_address),       //       master.address
		.master_readdata      (master_0_master_readdata),      //             .readdata
		.master_read          (master_0_master_read),          //             .read
		.master_write         (master_0_master_write),         //             .write
		.master_writedata     (master_0_master_writedata),     //             .writedata
		.master_waitrequest   (master_0_master_waitrequest),   //             .waitrequest
		.master_readdatavalid (master_0_master_readdatavalid), //             .readdatavalid
		.master_byteenable    (master_0_master_byteenable),    //             .byteenable
		.master_reset_reset   ()                               // master_reset.reset
	);

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (4),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (38),
		.UAV_BURSTCOUNT_W            (10),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) merlin_master_translator_0 (
		.clk                    (clk_0_clk),                       //                       clk.clk
		.reset                  (rst_controller_reset_out_reset),  //                     reset.reset
		.uav_address            (fpga_logic_master_address),       // avalon_universal_master_0.address
		.uav_burstcount         (fpga_logic_master_burstcount),    //                          .burstcount
		.uav_read               (fpga_logic_master_read),          //                          .read
		.uav_write              (fpga_logic_master_write),         //                          .write
		.uav_waitrequest        (fpga_logic_master_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (fpga_logic_master_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (fpga_logic_master_byteenable),    //                          .byteenable
		.uav_readdata           (fpga_logic_master_readdata),      //                          .readdata
		.uav_writedata          (fpga_logic_master_writedata),     //                          .writedata
		.uav_lock               (fpga_logic_master_lock),          //                          .lock
		.uav_debugaccess        (fpga_logic_master_debugaccess),   //                          .debugaccess
		.av_address             (),                                //      avalon_anti_master_0.address
		.av_waitrequest         (),                                //                          .waitrequest
		.av_burstcount          (),                                //                          .burstcount
		.av_byteenable          (),                                //                          .byteenable
		.av_read                (),                                //                          .read
		.av_readdata            (),                                //                          .readdata
		.av_readdatavalid       (),                                //                          .readdatavalid
		.av_write               (),                                //                          .write
		.av_writedata           (),                                //                          .writedata
		.av_beginbursttransfer  (1'b0),                            //               (terminated)
		.av_begintransfer       (1'b0),                            //               (terminated)
		.av_chipselect          (1'b0),                            //               (terminated)
		.av_lock                (1'b0),                            //               (terminated)
		.av_debugaccess         (1'b0),                            //               (terminated)
		.uav_clken              (),                                //               (terminated)
		.av_clken               (1'b1),                            //               (terminated)
		.uav_response           (2'b00),                           //               (terminated)
		.av_response            (),                                //               (terminated)
		.uav_writeresponsevalid (1'b0),                            //               (terminated)
		.av_writeresponsevalid  ()                                 //               (terminated)
	);

	mi_sdram_new_sdram_controller_0 new_sdram_controller_0 (
		.clk            (clk_0_clk),                                                 //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),                           // reset.reset_n
		.az_addr        (mm_interconnect_0_new_sdram_controller_0_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_new_sdram_controller_0_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_new_sdram_controller_0_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_new_sdram_controller_0_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_new_sdram_controller_0_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_new_sdram_controller_0_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_new_sdram_controller_0_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_new_sdram_controller_0_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr_addr),                                      //  wire.export
		.zs_ba          (sdram_wire_addr_ba),                                        //      .export
		.zs_cas_n       (sdram_wire_addr_cas_n),                                     //      .export
		.zs_cke         (sdram_wire_addr_cke),                                       //      .export
		.zs_cs_n        (sdram_wire_addr_cs_n),                                      //      .export
		.zs_dq          (sdram_wire_addr_dq),                                        //      .export
		.zs_dqm         (sdram_wire_addr_dqm),                                       //      .export
		.zs_ras_n       (sdram_wire_addr_ras_n),                                     //      .export
		.zs_we_n        (sdram_wire_addr_we_n)                                       //      .export
	);

	mi_sdram_mm_interconnect_0 mm_interconnect_0 (
		.sdram_clk_clk_clk_clk                                    (clk_0_clk),                                                 //                                  sdram_clk_clk_clk.clk
		.master_0_clk_reset_reset_bridge_in_reset_reset           (rst_controller_reset_out_reset),                            //           master_0_clk_reset_reset_bridge_in_reset.reset
		.new_sdram_controller_0_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                            // new_sdram_controller_0_reset_reset_bridge_in_reset.reset
		.master_0_master_address                                  (master_0_master_address),                                   //                                    master_0_master.address
		.master_0_master_waitrequest                              (master_0_master_waitrequest),                               //                                                   .waitrequest
		.master_0_master_byteenable                               (master_0_master_byteenable),                                //                                                   .byteenable
		.master_0_master_read                                     (master_0_master_read),                                      //                                                   .read
		.master_0_master_readdata                                 (master_0_master_readdata),                                  //                                                   .readdata
		.master_0_master_readdatavalid                            (master_0_master_readdatavalid),                             //                                                   .readdatavalid
		.master_0_master_write                                    (master_0_master_write),                                     //                                                   .write
		.master_0_master_writedata                                (master_0_master_writedata),                                 //                                                   .writedata
		.new_sdram_controller_0_s1_address                        (mm_interconnect_0_new_sdram_controller_0_s1_address),       //                          new_sdram_controller_0_s1.address
		.new_sdram_controller_0_s1_write                          (mm_interconnect_0_new_sdram_controller_0_s1_write),         //                                                   .write
		.new_sdram_controller_0_s1_read                           (mm_interconnect_0_new_sdram_controller_0_s1_read),          //                                                   .read
		.new_sdram_controller_0_s1_readdata                       (mm_interconnect_0_new_sdram_controller_0_s1_readdata),      //                                                   .readdata
		.new_sdram_controller_0_s1_writedata                      (mm_interconnect_0_new_sdram_controller_0_s1_writedata),     //                                                   .writedata
		.new_sdram_controller_0_s1_byteenable                     (mm_interconnect_0_new_sdram_controller_0_s1_byteenable),    //                                                   .byteenable
		.new_sdram_controller_0_s1_readdatavalid                  (mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid), //                                                   .readdatavalid
		.new_sdram_controller_0_s1_waitrequest                    (mm_interconnect_0_new_sdram_controller_0_s1_waitrequest),   //                                                   .waitrequest
		.new_sdram_controller_0_s1_chipselect                     (mm_interconnect_0_new_sdram_controller_0_s1_chipselect)     //                                                   .chipselect
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_0_reset_n),               // reset_in0.reset
		.clk            (clk_0_clk),                      //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
